version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-maven
    volumes:
      - ./JtProject:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=springproject
      - DB_USER=root
      - DB_PASSWORD=password
    ports:
      - 8080:8080
    command: sh -c "./mvnw clean install && java -jar /app/target/JtSpringProject-0.0.1-SNAPSHOT.jar"

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springproject
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
